# Generated by Django 3.1 on 2020-08-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='ptoto_1',
            new_name='photo_1',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='ptoto_20',
            new_name='photo_12',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='ptoto_10',
            new_name='photo_13',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='ptoto_11',
            new_name='photo_14',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='ptoto_12',
            new_name='photo_15',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='ptoto_13',
            new_name='photo_16',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='ptoto_14',
            new_name='photo_17',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='ptoto_15',
            new_name='photo_18',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='ptoto_16',
            new_name='photo_19',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='ptoto_17',
            new_name='photo_2',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='ptoto_18',
            new_name='photo_20',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='ptoto_19',
            new_name='photo_3',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='ptoto_2',
            new_name='photo_4',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='ptoto_3',
            new_name='photo_5',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='ptoto_4',
            new_name='photo_6',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='ptoto_5',
            new_name='photo_7',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='ptoto_6',
            new_name='photo_8',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='ptoto_7',
            new_name='photo_9',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='ptoto_main',
            new_name='photo_main',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='ptoto_8',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='ptoto_9',
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_10',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_11',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
